config/routes.rb
Rails.application.routes.draw do
  resources :recipes do 
    resources :comments, only: [:create, :destroy]
  end

  root to: 'pages#home'

#===============SESSION ROUTES==================

get '/login' =>'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

#=========== USER ROUTES =============

#create ###############################################################
  get '/users/new' => 'users#new', as: 'new_user'
  post '/users' => 'users#create'

  #read##################################################################

  get '/users' => 'users#index'
  
  get '/users/:id' => 'users#show', as: 'user'

  #update################################################################
  get '/users/:id/edit' => 'users#edit', as: 'edit_user'

  patch '/users/:id' => 'users#update'


  #DELETE##############################################################

  
#=========== RECIPE ROUTES =============




#create ###############################################################
# get '/recipes/new' => 'recipes#new', as: 'new_recipe'

# post '/recipes' => 'recipes#create'

# #read##################################################################
# get '/recipes' => 'recipes#index'


# get '/recipes/:id' => 'recipes#show', as: 'recipe'

# #update################################################################

# get '/recipes/:id/edit' => 'recipes#edit', as: 'edit_recipe'

# patch '/recipes/:id' => 'recipes#update'


# #DELETE##############################################################

# delete '/recipes/:id' => 'recipes#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :recipes

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :categories
  has_many :recipe_images
  has_many :comments
  belongs_to :user, optional: true
  validates :name, length: {minimum: 2}
end

app/models/recipe_image.rb
class RecipeImage < ApplicationRecord
  belongs_to :recipe, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :comments
  has_secure_password 
  
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user
  def fetch_user

    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end
    session[:user_id] = nil unless @current_user.present?
  end

  def check_if_logged_in
    unless @current_user.present?
      flash[:error] = 'You must login to perform this action'
      redirect_to login_path
    end

  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    
    #create a new comment for the post from current user
    @comment = @current_user.comments.new(comment_params)
    if !@comment.save
      flash[:notice] = @comment.errors.full_message.to_sentence
    end

    redirect_to recipe_path(params[:recipe_id])
  end

  def destroy 
    @recipe = Recipe.find params[:recipe_id]
    @comment = @recipe.comments.find params[:id]
    @comment.destroy
    redirect_to recipe_path(params[:recipe_id])
  end


  private

  def comment_params
    params.require(:comment).permit(:content).merge(recipe_id: params[:recipe_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :check_if_logged_in, except: [:index, :show]
  def new
    @recipe = Recipe.new
    @category = Category.all
  end

  def create
  
    @recipe = Recipe.create recipe_params

    @recipe.user_id = @current_user.id
    @recipe.save
    if @recipe.persisted?
      
      @recipe.categories << Category.find(params[:categories][:ids])
      redirect_to recipes_path
    else
      render :new
    end
    
  end

  def index
    @recipes = Recipe.all.order :created_at
  end

  def show
    @recipe = Recipe.find params[:id]
  end

  def edit
    @recipe = Recipe.find params[:id]

  end

  def update
    @recipe = Recipe.find params[:id]

    if@recipe.user_id != @current_user.id
      redirect_to login_path
      return
    end

    @recipe.update recipe_params
    # @recipe.categories.clear
    redirect_to recipe_path(params[:id])
  end

  def destroy
    Recipe.destroy params[:id]
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :method, :ingredients)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email]

    if user.present? && user.authenticate( params[:password] )

      session[:user_id] = user.id

      redirect_to root_path
    else
     flash[:error] = 'Invalid email or password'
     redirect_to login_path
    end 
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    
    @user = User.create user_params

    if params[:user][:image].present?
      #forward the uploaded image on to cloudinary
      response = Cloudinary::Uploader.upload params[:user][:image]
      @user.image = response['public_id']
    end

    @user.save

    if @user.persisted?
    redirect_to root_path
    else
      render :new
    end


  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]

    
  end

  def destroy
  end

  private
  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :bio)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<article>
  <p><%= comment.content %></p>
  <small>by: <%= link_to comment.user.name, user_path(comment.user.id) %></small>

  <% if @current_user.present? && comment.user_id == @current_user.id %>
  <%= link_to 'Delete', [comment.recipe, comment], method: 'delete' %> 
    <% end %>
</article>
<hr>

app/views/comments/_form.html.erb
<%= form_with model: [recipe, Comment.new], local:true do |f| %>
<%= f.label :content, "Add comment" %>
<br>
<%= f.text_area(:content, size: '30x6')%>
<br>
<%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <div id="page-container">
    <div id="content-wrap">
      <div class="header">
        <div class="header-content">
          <h1>Not Quite a Food Blog </h1>
          <nav>
            <div class="links">
              
            <% if @current_user.present?%>
              <strong>Welcome, <%= @current_user.name%></strong>
              |
              <%= link_to 'Home', root_path %> 
              |
              <%= link_to 'All Recipes', recipes_path %> 
              |
              <%= link_to 'All Users', users_path %> 
              |
              <%= link_to 'Create Recipe', new_recipe_path %>
              |
              <%= link_to 'Logout', login_path, method: 'delete' %>
              |

            <% else %>
              <%= link_to 'Home', root_path %> 
              |
              <%= link_to 'All Recipes', recipes_path %> 
              |
              <%= link_to 'All Users', users_path %> 
              |
              <%= link_to 'Login', login_path %>
              |
              <%= link_to 'Signup', new_user_path %>
              |
            <% end %>

            </div>
          </nav>
        </div>
      </div>
      
      <div class="content">
        <%= yield %>
      </div> 
  
    </div>
    <footer>
      &copy; Not Quite a Food Blog 2022
    </footer>
    </div>  
  </body>
</html>

app/views/pages/home.html.erb
<div class="homepage_header">
  <h2> The Worlds Most Useful Useless Recipe database!</h2>
  <p>You will find a world of recipes from people around the globe</p>
</div>


<div class="homepage-content">
<h3>Trending Recipes:</h3>

<ul>

<% @recipes.each do |recipe|%>
  <li class='homepage-links'>
  <%= link_to recipe.name, recipe_path(recipe.id) %>
    <br>
   <p class='li-p'><%= recipe.description %></p> 
    
  </li>
<% end %>
</ul>
</div>

app/views/recipes/_form.html.erb
<% if @recipe.errors.any?%>
  <ul>
    <% @recipe.errors.full_messages.each do |e|%>
      <li>
        <%= e %>  
      </li>
      <% end %>
  </ul>
<% end %>


<%= form_with model: @recipe, local: true do |f| %>

  <%= f.label :name%>
  <br>
  <%= f.text_field :name %>
  <br>

  <%= f.label :description%>
  <br>
  <%= f.text_field :description %>
  <br>

  <%= f.label :ingredients%>
  <br>
  <%= f.text_area :ingredients %>
  <br>

  <%= f.label :method%>
  <br>
  <%= f.text_area :method %>
  <br>

  <%= f. submit %>

<% end %>

 <%#<%= label_tag :category %>
  
  <%# collection_check_boxes :categories, :ids, @category.all, :id, :name, include_hidden: false   %>

app/views/recipes/edit.html.erb
<h2>Edit Recipe: <%= @recipe.name %> </h2>

  <%= render partial: 'form' %>

app/views/recipes/index.html.erb
<h1>The complete collection</h1>

<div >
<ul>
<% @recipes.each do |r|%>
  <li class="index-recipes">
    <%= link_to r.name, recipe_path(r) %>
    <% if @current_user.present? && r.user_id == @current_user.id %>
      (<%= link_to 'Edit', edit_recipe_path(r.id) %>)
    <% end %>
    <br>
    <%= r.description%>
    <br>
  </li>
<% end %>
</ul>
</div>

app/views/recipes/new.html.erb
<h2>Add New Recipe</h2>

<%= render partial: 'form'%>

app/views/recipes/show.html.erb
<h2><%= @recipe.name %></h2>


    <% if @current_user.present? && @recipe.user_id == @current_user.id %>
       <%= link_to 'Edit', edit_recipe_path(@recipe.id) %>
      <%= link_to 'Delete', recipe_path, method: 'delete' %>
    <% end %>
<br><br>

<p>
  <strong>Creator of recipe: </strong>
  <br>
    <%= @recipe.user.name %>
  </p>
<br>

<div class="recipe-images">
<% @recipe.recipe_images.each do |image|%>
      <%= image_tag image.image_url %>
  <% end %>
</div>
  


<p>
  <strong>Description: </strong>
  <br>
    <%= @recipe.description%>
  </p>
<br>

<p>
  <strong>Categories: </strong>
  <br>
  <% @recipe.categories.each do |cat|%>
    <ul>
      <li>
        <%= cat.name %>
      </li>
    </ul>
  <% end %>
</p>
<br>

<p>
  <strong>Ingredients: </strong>
  <br>
    <%= @recipe.ingredients.gsub("\n", "<br>").html_safe%>
</p>
<br>
<p>
  <strong>Method: </strong>
  <br>
    <%= @recipe['method'].gsub("\n", "<br>").html_safe%>
  </p>
<br>

<p class="comment-section">
  <strong>Comments:</strong>
  <%= render @recipe.comments.includes(:user).order(id: :desc) %>
  <% if @current_user.present? %>
    <%= render partial: 'comments/form', locals: { recipe: @recipe }%>
  <% end %>
  
</p>

app/views/session/new.html.erb
<h2>Login</h2>

<% if flash[:error]%>
  <br><strong>
    <%= flash[:error]%>
  </strong>
  <br><br>    

  <% end %>

<%= form_with url: login_path, local: true do |f|%>
  <%= f.label :email%>
  <br>
  <%= f.text_field :email%>
  <br><br>
  
  <%= f.label :password%>
  <br>
  <%= f.password_field :password%>
  <br><br>

  <%= f.submit 'Login'%>

<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any?%>
  <ul>
    <% @user.errors.full_messages.each do |e|%>
      <li>
        <%= e %>  
      </li>
      <% end %>
  </ul>
<% end %>


<%= form_with model: @user, local: true, html: { multipart: true } do |f| %>

  <%= f.label :name%>
  <br>
  <%= f.text_field :name %>
  <br>

  <%= f.label :email%>
  <br>
  <%= f.text_field :email %>
  <br>

  <%= f.label :bio%>
  <br>
  <%= f.text_area :bio %>
  <br>

  <%= f.label :password%>
  <br>
  <%= f.password_field :password %>
  <br>

  <%= f.label :password_confirmation%>
  <br>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.label :image, 'Profile Photo URL'%>
  <br>
  <%= f.file_field :image %>
  <br>



  <%= f. submit 'Signup' %>

<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h2>All Users on the Database</h2>
<div class="users_index">
<ul >
  <% @users.each do |u|%>
    <li>
      <%= cl_image_tag u.image, height: 200, width: 200, crop: 'fill', alt: u.name%>
      <br>
      <%= link_to u.name, user_path(u.id) %>
    </li>
    <br>
  <% end %>
</ul>

</div>

app/views/users/new.html.erb
<h2>Welcome! Enter Your Details To Sign Up!</h2>

<%= render partial: 'form'%>

app/views/users/show.html.erb
<div class="user_index">
  <%= link_to 'Edit Profile', edit_user_path %>
  
  <h2><%= @user.name %></h2>


  <%= cl_image_tag @user.image, height: 200, width: 200, crop: 'fill', alt: @user.name %>
  <br>
  <p>
    <strong>Bio:</strong>
    <%= @user.bio%>
  </p>
  <br>
  <p>
    <strong>Get in touch:</strong>
    <%= @user.email%>
  </p>
  <br>
  <p>
  <% if @user.recipes%>
      <strong>My recipes:</strong>
      <br>
  
      <%@user.recipes.each do |recipe| %>
      <%= link_to recipe.name, recipe_path(recipe.id) %>
      <br>
      <% end %>
    <% end %>
    
    
    
  </p>



</div>